const usersSeeds = [{
    // id = 1
    account_name: 'vlad',
    nickname: 'vlad',
    first_name: 'Vlad',
    last_name: 'Ivanov',
    email: 'vlad.ivanov@gmail.com',
    phone_number: '+79161234567',
    birthday: new Date(1980, 1, 12),
    about: 'I am blockchain developer',
    country: 'Russia',
    city: 'Moscow',
    address: 'Tverskaya, 1',
    mood_message: 'Be always positive',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: 'EOS7u9ckBz7Qi3LVsN7kM9wViX7Qya7XL5eWZg3vg6nKARyk8xV8U',
    currency_to_show: 'ETH',
    first_currency: 'BTC',
    first_currency_year: '2008',
    personal_website_url: 'https://www.blockchain.com/',
    private_key: '5Hq7Bb6ntCXJzEKSmELemLYhs3iUGX7wBh3CPUSgmEBLnnPSpX6',
  },
  {
    // id = 2
    account_name: 'jane',
    nickname: 'jane',
    first_name: 'Jane',
    last_name: 'Ivanova',
    email: 'jane.ivanova@example.com',
    phone_number: '+19161234567',
    birthday: new Date(1975, 3, 20),
    about: 'I am a CEO of big blockchain company',
    country: 'US',
    city: 'LA',
    address: 'LA street, 12',
    mood_message: 'Everything is always ok',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: 'EOS5SURs5Evb2e3ybaxFdRvLjLzqHUixx7SJEHz1uqTLy36C7MRsm',
    currency_to_show: 'EOS',
    first_currency: 'ETH',
    first_currency_year: '2012',
    personal_website_url: 'https://bitcointalk.org/'
  },
  {
    // id = 3
    account_name: 'petr',
    nickname: 'petr',
    first_name: 'Petr',
    last_name: 'Pavlov',
    email: 'petr.pavlov@example.com',
    phone_number: '+19161234999',
    birthday: new Date(1969, 1, 11),
    about: 'I am a crypto trader',
    country: 'US',
    city: 'NY',
    address: 'NY street, 1',
    mood_message: 'Catch the candle',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: 'sample_public_key',
    currency_to_show: 'BTH',
    first_currency: 'BTH',
    first_currency_year: '2009',
    personal_website_url: 'https://example.com/'
  },
  {
    // id = 4
    account_name: 'rokky',
    nickname: 'rokky',
    first_name: 'Rokky',
    last_name: 'Semenov',
    email: 'rokky.semenov@example.com',
    phone_number: '+19161234111',
    birthday: new Date(1991, 10, 1),
    about: 'Im completely beginner in blockchain',
    country: 'RU',
    city: 'SPB',
    address: 'Nevsky street, 8',
    mood_message: 'Blockchain rocks!',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: 'sample_public_key_2',
    currency_to_show: 'ETH',
    first_currency: 'ETH',
    first_currency_year: '2015',
    personal_website_url: 'https://example2.org/'
  },
];

module.exports = usersSeeds;