const accountsData = require('../../config/accounts-data');

const usersSeeds = [{
    // id = 1
    account_name: accountsData.vlad.account_name,
    nickname: accountsData.vlad.account_name,
    first_name: 'Vlad',
    last_name: 'Ivanov',
    email: 'vlad.ivanov@gmail.com',
    phone_number: '+79161234567',
    birthday: new Date(1980, 1, 12),
    about: 'I am blockchain developer',
    country: 'Russia',
    city: 'Moscow',
    address: 'Tverskaya, 1',
    mood_message: 'Be always positive',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: accountsData.vlad.activePubKey,
    currency_to_show: 'ETH',
    first_currency: 'BTC',
    first_currency_year: '2008',
    personal_website_url: 'https://www.blockchain.com/',
    private_key: accountsData.vlad.activePk,
  },
  {
    // id = 2
    account_name: accountsData.jane.account_name,
    nickname: accountsData.jane.account_name,
    first_name: 'Jane',
    last_name: 'Ivanova',
    email: 'jane.ivanova@example.com',
    phone_number: '+19161234567',
    birthday: new Date(1975, 3, 20),
    about: 'I am a CEO of big blockchain company',
    country: 'US',
    city: 'LA',
    address: 'LA street, 12',
    mood_message: 'Everything is always ok',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: accountsData.jane.activePubKey,
    currency_to_show: 'EOS',
    first_currency: 'ETH',
    first_currency_year: '2012',
    personal_website_url: 'https://bitcointalk.org/',
    private_key: accountsData.jane.activePk,
  },
  {
    // id = 3
    account_name: accountsData.petr.account_name,
    nickname: accountsData.petr.account_name,
    first_name: 'Petr',
    last_name: 'Pavlov',
    email: 'petr.pavlov@example.com',
    phone_number: '+19161234999',
    birthday: new Date(1969, 1, 11),
    about: 'I am a crypto trader',
    country: 'US',
    city: 'NY',
    address: 'NY street, 1',
    mood_message: 'Catch the candle',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: accountsData.petr.activePubKey,
    currency_to_show: 'BTH',
    first_currency: 'BTH',
    first_currency_year: '2009',
    personal_website_url: 'https://example.com/',
    private_key: accountsData.petr.activePk,
  },
  {
    // id = 4
    account_name: accountsData.rokky.account_name,
    nickname: accountsData.rokky.account_name,
    first_name: 'Rokky',
    last_name: 'Semenov',
    email: 'rokky.semenov@example.com',
    phone_number: '+19161234111',
    birthday: new Date(1991, 10, 1),
    about: 'Im completely beginner in blockchain',
    country: 'RU',
    city: 'SPB',
    address: 'Nevsky street, 8',
    mood_message: 'Blockchain rocks!',
    created_at: new Date(),
    updated_at: new Date(),
    avatar_filename: null,
    public_key: accountsData.rokky.activePubKey,
    currency_to_show: 'ETH',
    first_currency: 'ETH',
    first_currency_year: '2015',
    personal_website_url: 'https://example2.org/',
    private_key: accountsData.rokky.activePk
  },
];

module.exports = usersSeeds;